name: Tasmota CI (Kettle Companion)

on:
  push:

jobs:
  tasmota:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U platformio
        platformio upgrade --dev
        platformio update
    - name: Run PlatformIO
      run: platformio run -e tasmota
    - uses: actions/upload-artifact@v2
      with:
        name: firmware
        path: ./build_output

  tasmota-minimal:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U platformio
        platformio upgrade --dev
        platformio update
    - name: Run PlatformIO
      run: platformio run -e tasmota-minimal
    - uses: actions/upload-artifact@v2
      with:
        name: firmware
        path: ./build_output

  tasmota-minimal-trampoline:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U platformio
        platformio upgrade --dev
        platformio update
    - name: Run PlatformIO
      run: platformio run -e tasmota-minimal-trampoline
    - uses: actions/upload-artifact@v2
      with:
        name: firmware
        path: ./build_output

